link: item_int.o list.o stackList.o queueStack.o main.o
	gcc item_int.o list.o stackList.o queueStack.o main.o -o queue.exe

item_int.o:
	gcc -c item_int.c

list.o:
	gcc -c list.c

stackList.o:
	gcc -c stackList.c

queueStack.o:
	gcc -c queueStack.c

main.o:
	gcc -c main.c

clean:
	rm -f *.o *.exe
